#!/bin/sh
PREFIX=SkillerWhaleSync
mkdir -p build
for build in windows-amd64 linux-amd64 darwin-amd64 linux-arm64 darwin-arm64 ; do
  export GOOS=`echo $build | cut -d- -f1`
  export GOARCH=`echo $build | cut -d- -f2`
  go build -o build/$PREFIX-$GOOS-$GOARCH
done
mv build/$PREFIX-windows-amd64 build/$PREFIX-windows-amd64.exe
