name: Build and package
on:
  push:
    branches: [master]
jobs:
  build:
    name: SkillerWhaleSync on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          ./gradlew build
          native-image --no-server -jar build/libs/SkillerWhaleSync.jar -H:IncludeResources=logo
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: SkillerWhaleSync-${{ matrix.os }}
          path: |
            build/libs/SkillerWhaleSync.jar
            SkillerWhaleSync*
            build/reports/test/test
            build/test-results
  release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Display fetched artifacts
        run: ls -R
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            SkillerWhaleSync-*
