name: Build and package
on:
  push:
    branches: [main]
jobs:
  build:
    name: SkillerWhaleSync on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: ./gradlew nativeCompile
      - name: Rename native build
        working-directory: build/native/nativeCompile
        run: mv SkillerWhaleSync SkillerWhaleSync-${{ runner.os }}-${{ runner.arch }}
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          path: build
  release:
    name: "Pre-release binary"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download build
      - name: Display fetched artifacts
        run: ls -R
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifact/build/libs/SkillerWhaleSync.jar
            artifact/build/native/nativeCompile/SkillerWhaleSync-*
