name: Build and package
on:
  push:
    branches: [main, go-rewrite]
    tags:
      - "v*"
jobs:
  build:
    name: SkillerWhaleSync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Test
        run: go test
      - name: Build
        run: ./buildAll
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          path: build
  release:
    name: "Pre-release binary"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download build
      - name: Display fetched artifacts
        run: ls -R
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        name: Create pre-release from main
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifact/SkillerWhaleSync-*
      - if: "startsWith(github.ref, 'refs/tags/v')"
        name: Create tagged release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            artifact/SkillerWhaleSync-*
