name: Build & Release
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Test and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - name: Build
        run: ./buildAll
      - name: Test
        run: go generate && go test
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          path: build

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download build
      - name: Display fetched artifacts
        run: ls -R
      # Release tags that aren't v... are pre-release, named after their branch
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        name: Create pre-release from main
        uses: "softprops/action-gh-release@v2"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_commitish: ${{github.ref_name}}
          tag_name: "PRERELEASE-${{ github.ref_name }}"
          prerelease: true
          name: "Development build"
          generate_release_notes: true
          files: |
            artifact/SkillerWhaleSync-*
      # Release tags starting v... are releases, named as per the tag
      - if: "startsWith(github.ref, 'refs/tags/v')"
        name: Create tagged release
        uses: "softprops/action-gh-release@v2"
        with:
          prerelease: false
          generate_release_notes: true
          make_latest: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            artifact/SkillerWhaleSync-*

  build-and-push-image:
    name: Build and push Docker image
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # this uses &&/|| as a ternary: if the ref isn't a tag starting with `v` then the prefix 'PRELEASE-' is added, if not no prefix added
          # see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example
          build-args: |
            release=${{ !startsWith(github.ref, 'refs/tags/v') && 'PRERELEASE-' || '' }}${{ github.ref_name }}
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
