name: Test, build, release
on: push
jobs:
  build:
    name: "Test and build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Build
        run: ./buildAll
      - name: Test
        run: go generate && go test
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          path: build
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        name: Download build
      - name: Display fetched artifacts
        run: ls -R
      # Release tags that aren't v... are pre-release, named after their branch
      - if: "!startsWith(github.ref, 'refs/tags/v')"
        name: Create pre-release from main
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: true
          title: "Development Build"
          files: |
            artifact/SkillerWhaleSync-*
      # Release tags starting v... are releases, named as per the tag
      - if: "startsWith(github.ref, 'refs/tags/v')"
        name: Create tagged release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            artifact/SkillerWhaleSync-*
